#!/bin/bash
set -e

cd "$(dirname "$0")"
source bootstrap/lib.sh

usage() {
  cat << EOF
Usage: ./shutdown.sh [tier]

Tiers (each includes everything from the tiers above it):
  (none)      Stop and remove containers only. Named volumes and images
              are left untouched. Safe to run after every session.
  --clean     + prune dangling images, stopped containers, unused
              networks and build cache. Non-destructive to your data —
              just reclaims disk space.
  --volumes   + delete the mariadb-data and seaweedfs-data volumes
              (wipes the dev database and any uploaded/CAD files).
  --images    + remove every image used by this project (next startup
              re-pulls them all — slow, but no data loss).
  --all       Complete fresh state: containers, volumes, images, AND
              the local frappe-bench/ folder (fully regenerated by
              bootstrap/setup-bench.sh anyway). After this, ./install.sh
              behaves exactly like a first-ever run.
EOF
}

TIER="${1:-}"
case "$TIER" in
  ""|--clean|--volumes|--images|--all) ;;
  -h|--help) usage; exit 0 ;;
  *) echo "Unknown option: $TIER"; usage; exit 1 ;;
esac

if [ "$DOCKER_STATUS" != "0" ]; then
  echo "Docker isn't reachable (not installed, or the daemon isn't running)."
  echo "Nothing to shut down."
  exit 0
fi

require_env_file

# --- Work out, up front, exactly what "docker compose down" flags we'll
# use — and get any destructive confirmations out of the way BEFORE
# touching anything. If the user declines, we still fall back to a plain
# container stop rather than doing nothing.
DOWN_FLAGS=""

if [ "$TIER" == "--volumes" ] || [ "$TIER" == "--all" ]; then
  echo "This will permanently delete the mariadb-data and seaweedfs-data"
  echo "volumes — your dev database and any uploaded/CAD files in SeaweedFS."
  echo "The vscode-server cache volume is also cleared, but that's harmless:"
  echo "it just gets re-seeded automatically the next time you run"
  echo "./startup.sh or ./install.sh."
  if [ "$TIER" == "--volumes" ]; then
    echo ""
    echo "Note: frappe-bench/ on disk will NOT be touched by --volumes alone,"
    echo "so it will still look provisioned (site + apps present) afterward —"
    echo "but pointing at a database that no longer exists. ./startup.sh will"
    echo "prompt you about this. Use --all instead for a fully consistent"
    echo "fresh state."
  fi
  echo ""
  if confirm_typed "Delete mariadb-data and seaweedfs-data volumes?" "DELETE"; then
    DOWN_FLAGS="$DOWN_FLAGS -v"
  else
    echo "Skipping volume deletion — volumes will be left in place."
  fi
fi

if [ "$TIER" == "--images" ] || [ "$TIER" == "--all" ]; then
  echo ""
  echo "This will remove every image used by this project. Next startup"
  echo "will need to re-pull them all (mariadb, redis, seaweedfs, frappe/bench)."
  echo ""
  if confirm "Remove all project images?"; then
    DOWN_FLAGS="$DOWN_FLAGS --rmi all"
  else
    echo "Skipping image removal — images will be left in place."
  fi
fi

if [ "$TIER" == "--all" ]; then
  echo ""
  echo "--all also deletes the local frappe-bench/ folder (app code, venv,"
  echo "and site config inside it — fully regenerated by setup-bench.sh)."
  echo ""
  if confirm_typed "Wipe frappe-bench/ too, for a true fresh-clone state?" "DELETE EVERYTHING"; then
    WIPE_BENCH=1
  else
    echo "Skipping frappe-bench/ removal."
  fi
fi

echo ""
echo "Stopping containers..."
# shellcheck disable=SC2086
$DOCKER_COMPOSE down $DOWN_FLAGS
echo "Done."

if [ "$TIER" == "--clean" ] || [ "$TIER" == "--all" ]; then
  echo ""
  echo "Removing dangling images, unused networks, and build cache..."
  $DOCKER system prune -f
fi

if [ "${WIPE_BENCH:-0}" == "1" ]; then
  rm -rf "$REPO_ROOT/frappe-bench"
  rm -f "$REPO_ROOT/bootstrap/.bootstrap.log"
  echo "frappe-bench/ removed. Run ./install.sh to provision from scratch."
fi

echo ""
echo "Remaining volumes:"
$DOCKER volume ls
